app:
  cors:
    allowed-origins:
      - "https://nursepro.vercel.app"
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://prod-db-host:3306/nurse_pro_db?useSSL=true&serverTimezone=UTC}
    username: ${DB_USERNAME:prod_user}
    password: ${DB_PASSWORD:prod_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    jwt:
      secret: ${JWT_SECRET:your-prod-jwt-secret-key}
      expiration: 86400000
server:
  port: 8080
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    com.surf.nursepro: INFO
    org.springframework: WARN