app:
  cors:
    allowed-origins:
      - "http://localhost:*"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nurse_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: your-secure-jwt-secret-key-here-32-chars-minimum
  expiration: 86400000 # 24 hours in milliseconds
  refresh:
    expiration: 604800000 # 7 days in milliseconds
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
springdoc:
  packages-to-scan: com.surf.nursepro.nurse_pro_api.controller
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: alpha
    tagsSorter: alpha
    display-request-duration: true
logging:
  level:
    root: INFO
    com.surf.nursepro: DEBUG
    org.springdoc: DEBUG